apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-app
  template:
    metadata:
      labels:
        app: cart-app
    spec:
      containers:
        - name: cart-image
          image: vinod5982/cart-app:v1
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "200m"
